# .goreleaser.yaml
version: 2

project_name: git-wth

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}
    main: .

archives:
  - formats: [tar.gz]
    id: archive
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "Windows" }}win
      {{- else if eq .Os "Darwin" }}mac
      {{- else if eq .Os "Linux" }}linux
      {{- else }}{{ tolower .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
    wrap_in_directory: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "Windows" }}win
      {{- else if eq .Os "Darwin" }}mac
      {{- else if eq .Os "Linux" }}linux
      {{- else }}{{ tolower .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - formats: [binary]
    id: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "Windows" }}win
      {{- else if eq .Os "Darwin" }}mac
      {{- else if eq .Os "Linux" }}linux
      {{- else }}{{ tolower .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

sboms:
  - artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_sbom.spdx.json"

release:
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
